### PR TITLE
Development

### PR DESCRIPTION
**Pull request by nijeesh4all**
Hi Aswin,
I heard about you on the news today. What you are doing is amazing it's an honor that people like are part of the community. When the news channel showed the code I knew it was written on ROR so I thought I should help in any way I can. This is just a readme update. if there are any open issues you are working on please let me know.

### CODE REVIEW

**Comment by aswinmohanme** [comment]
The rake admin task should need `password` and `password_confirmation`

**Comment by nijeesh4all** [comment]
acutally we are creating it from the terminal right, so we can see whats the password what password we are giving in in plain text. So i dont think that will be necessory. If you think so, i will add.

**Comment by aswinmohanme** [comment]
Also the master branch contains production ready code only, push to develop

**Comment by nijeesh4all** [comment]
Sure.
can you please make a small, condribution guidelines. if you do it, i could ask a few more people to join in.

**Pull request closed without merging**
